version: '3'

services:
    db:
        image: postgres
        environment: 
            POSTGRES_HOST_AUTH_METHOD: "trust"
    web:
        build: .
        command: python coctails/manage.py runserver 0.0.0.0:8000
        env_file: 
            - .env
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on: 
            - db
